# Generated by Django 5.1.6 on 2025-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tests',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
